export const COUNTRY_TIMEZONE = [
  { value: 'America/New_York', label: 'United States' },
  { value: 'America/Toronto', label: 'Canada' },
  { value: 'Europe/London', label: 'United Kingdom' },
  { value: 'Australia/Sydney', label: 'Australia' },
  { value: 'Asia/Calcutta', label: 'India' }, // Corrected to 'Asia/Calcutta'
  { value: 'Europe/Berlin', label: 'Germany' },
  { value: 'Europe/Paris', label: 'France' },
  { value: 'Asia/Tokyo', label: 'Japan' },
  { value: 'America/Sao_Paulo', label: 'Brazil' },
  { value: 'Africa/Johannesburg', label: 'South Africa' },
  { value: 'Asia/Shanghai', label: 'China' },
  { value: 'Europe/Moscow', label: 'Russia' },
  { value: 'Europe/Rome', label: 'Italy' },
  { value: 'America/Mexico_City', label: 'Mexico' },
  { value: 'Asia/Dubai', label: 'United Arab Emirates' },
  { value: 'Europe/Madrid', label: 'Spain' },
  { value: 'Asia/Bangkok', label: 'Thailand' },
  { value: 'Asia/Seoul', label: 'South Korea' },
  { value: 'America/Argentina/Buenos_Aires', label: 'Argentina' },
  { value: 'Africa/Cairo', label: 'Egypt' },
  { value: 'Asia/Singapore', label: 'Singapore' },
  { value: 'America/Los_Angeles', label: 'United States (Los Angeles)' },
  { value: 'Europe/Zurich', label: 'Switzerland' },
  { value: 'Europe/Brussels', label: 'Belgium' },
  { value: 'Europe/Amsterdam', label: 'Netherlands' },
  { value: 'Asia/Karachi', label: 'Pakistan' },
  { value: 'Africa/Lagos', label: 'Nigeria' },
  { value: 'America/Chicago', label: 'United States (Chicago)' },
  { value: 'Europe/Stockholm', label: 'Sweden' },
  { value: 'Europe/Oslo', label: 'Norway' },
  { value: 'Europe/Warsaw', label: 'Poland' },
  { value: 'Asia/Hong_Kong', label: 'Hong Kong' },
  { value: 'Europe/Vienna', label: 'Austria' },
  { value: 'Asia/Kuala_Lumpur', label: 'Malaysia' },
  { value: 'Europe/Athens', label: 'Greece' },
  { value: 'Europe/Copenhagen', label: 'Denmark' },
  { value: 'Asia/Jakarta', label: 'Indonesia' },
  { value: 'Asia/Manila', label: 'Philippines' },
  { value: 'Africa/Nairobi', label: 'Kenya' },
  { value: 'America/Bogota', label: 'Colombia' },
  { value: 'Europe/Lisbon', label: 'Portugal' },
  { value: 'Europe/Dublin', label: 'Ireland' },
  { value: 'Asia/Dhaka', label: 'Bangladesh' },
  { value: 'Africa/Addis_Ababa', label: 'Ethiopia' },
  { value: 'Asia/Tehran', label: 'Iran' },
  { value: 'Africa/Algiers', label: 'Algeria' },
  { value: 'Asia/Kathmandu', label: 'Nepal' },
  { value: 'Africa/Accra', label: 'Ghana' },
  { value: 'Europe/Sofia', label: 'Bulgaria' },
  { value: 'America/Caracas', label: 'Venezuela' },
  { value: 'Africa/Harare', label: 'Zimbabwe' },
  { value: 'America/Lima', label: 'Peru' },
  { value: 'Asia/Tashkent', label: 'Uzbekistan' },
  { value: 'America/Santiago', label: 'Chile' },
  { value: 'Asia/Riyadh', label: 'Saudi Arabia' },
  { value: 'America/Montevideo', label: 'Uruguay' },
  { value: 'Africa/Dakar', label: 'Senegal' },
  { value: 'Europe/Helsinki', label: 'Finland' },
  { value: 'Asia/Kuwait', label: 'Kuwait' },
  { value: 'America/Guayaquil', label: 'Ecuador' },
  { value: 'Africa/Maputo', label: 'Mozambique' },
  { value: 'Europe/Bucharest', label: 'Romania' },
  { value: 'Asia/Baghdad', label: 'Iraq' },
  { value: 'Africa/Luanda', label: 'Angola' },
  { value: 'Asia/Beirut', label: 'Lebanon' },
  { value: 'Africa/Mogadishu', label: 'Somalia' },
  { value: 'America/La_Paz', label: 'Bolivia' },
  { value: 'Europe/Budapest', label: 'Hungary' },
  { value: 'Asia/Amman', label: 'Jordan' },
  { value: 'Asia/Doha', label: 'Qatar' },
  { value: 'Asia/Taipei', label: 'Taiwan' },
  { value: 'America/Asuncion', label: 'Paraguay' },
  { value: 'Europe/Belgrade', label: 'Serbia' },
  { value: 'Asia/Muscat', label: 'Oman' },
  { value: 'America/Belize', label: 'Belize' },
  { value: 'Africa/Abidjan', label: 'Ivory Coast' },
  { value: 'America/Kingston', label: 'Jamaica' },
  { value: 'Asia/Vientiane', label: 'Laos' },
  { value: 'Africa/Ndjamena', label: 'Chad' },
  { value: 'America/Port_of_Spain', label: 'Trinidad and Tobago' },
  { value: 'Asia/Manama', label: 'Bahrain' },
  { value: 'America/Havana', label: 'Cuba' },
  { value: 'America/Guatemala', label: 'Guatemala' },
  { value: 'Europe/Chisinau', label: 'Moldova' },
  { value: 'America/Tegucigalpa', label: 'Honduras' },
  { value: 'Africa/Conakry', label: 'Guinea' },
  { value: 'Asia/Chongqing', label: 'Chongqing' },
  { value: 'Africa/Banjul', label: 'Gambia' },
  { value: 'America/Belmopan', label: 'Belize' },
  { value: 'Asia/Yangon', label: 'Myanmar' },
  { value: 'America/Porto_Alegre', label: 'Brazil (Porto Alegre)' },
  { value: 'America/Nassau', label: 'The Bahamas' },
  { value: 'America/Bridgetown', label: 'Barbados' },
  { value: 'Africa/Douala', label: 'Cameroon' },
  { value: 'Asia/Chennai', label: 'India (Chennai)' },
  { value: 'Africa/Tunis', label: 'Tunisia' },
  { value: 'America/Panama', label: 'Panama' },
  { value: 'Asia/Sana', label: 'Yemen' },
  { value: 'Africa/Bujumbura', label: 'Burundi' },
  { value: 'America/Puerto_Rico', label: 'Puerto Rico' },
  // Add more countries as needed...
];

export const TRAFFIC_SOURCES = [
  // {
  //   id: 'any',
  //   label: 'Any',
  // },
  {
    id: 'direct',
    label: 'Direct',
  },
  {
    id: 'google',
    label: 'Organic - Google',
  },
  {
    id: 'yahoo',
    label: 'Organic - Yahoo',
  },
  {
    id: 'bing',
    label: 'Organic - Bing',
  },
  {
    id: 'youtube',
    label: 'Organic - Youtube',
  },
  {
    id: 'reddit',
    label: 'Organic - Reddit',
  },
  {
    id: 'paid_google',
    label: 'Paid Search - Google',
  },
  {
    id: 'paid_bing',
    label: 'Paid Search - Bing',
  },
  {
    id: 'paid_linkedin',
    label: 'Paid Search - LinkedIn',
  },
  {
    id: 'paid_meta',
    label: 'Paid Search - Meta',
  },
  {
    id: 'paid_youtube',
    label: 'Paid Search - Youtube',
  },
  {
    id: 'paid_reddit',
    label: 'Paid Search - Reddit',
  },
];
